### ISSUE TITLE
SPIKE: Use OID as primary object identifier?

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/YUL-DC#15]
**ISSUE**
The OID (Object Identifier) is current the primary ID used in Ladybird and DL to connect metadata, structure, and images.  
1. Can we continue using this ID going forward?
2. How will we mint IDs for Valkyrie 
3. Will we need to continue minting IDs for Ladybird (other YUL digital ingests, not Beinecke) after October 2020?
4. Can we "bump the sequence" in the new system to leave room for new Ladybird items (see 3)
5. [BONUS] How big a jump might we need in the sequence.

**OUTCOME**
- [x] Summarize any discussion, research, and experimentation and report back to team at sprint review
- [x] Identify any outstanding issues with using OIDs, or propose an alternate solution.

**Comment by DraxIndustries79** [comment]
Yale to have internal conversation to make a provisional decision on this.

**Comment by mikeapp** [comment]
Highest published OID is currently 16945676

**Comment by mikeapp** [comment]
Per conversation with George we might jump to 40- or 50-million prefix, which would exceed our capacity to ingest over the next 1.5-2 years.
