### ISSUE TITLE
S3 or other storage for P-TIFFs

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/YUL-DC#16]

**Comment by mikeapp** [comment]
Cost:
In testing our museums have seen the PTIFFs coming in at around 10% of the size of the masters.  S3 list price is $23/TB/month.   Storage@Yale is less expensive than S3.

Convenience:
Using Storage@Yale the DevOps team can clone the production filesystem to the UAT and Test environments without additional cost (filesystem magic tracks the changes in those environments so we're not actually using more storage).

**Comment by bobrice** [comment]
ITS also offers object storage in their StorageGrid(waiting on pricing) and YUL-IT has an account with Wasabi($3.96/TB/mo) for less expensive cloud storage options.

**Comment by mark-dce** [comment]
Access Masters:

Decision Criteria (straw dog rankings)
40% Reliability
30% Cost (Note this covers storage, ingress and egress costs are free)
10% Ease / flexibility of connection to containers (might need to build an S3 adapter for Valkyrie)
10% Performance (object stores might have a concurrency advantage)
5% Single item backup/restore (or versioning of deleted items)
5% Bulk backup/restore

Current contenders
* AWS S3
* Storage Grid (object storage)
* Storage@Yale (mountable file system)
* Wasabi

Tentative Decision (Access Masters)
* Move forward with Storage@Yale, 
* Test Storage Grid in parallel and determine how similar compatible it is with S3 (complete testing by Mon 4/13)
* Refactor for Storage Grid if there are compelling benefits on 4/13

Tentative Decision (Ptiffs - approximately 16%-20% total size of access masters)
* Move forward with S3, 
* Test Storage Grid in parallel and determine how similar compatible it is with S3 (complete testing by Mon 4/13) 
    * especially consider whether there are reliability / connectivity differences between S3 and Storage Grid
* Refactor for Storage Grid if there are compelling benefits on 4/13
