### ISSUE TITLE
SPIKE: Draft a plan for how to store access master images

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/YUL-DC#17]
We plan to store access masters (cropped TIFFs) on Storage@Yale which has a 100TB per volume limit.

Beinecke has < 100TB (~25% of total current content)
YUL content will bump us over the 100TB limit

Newly ingested content will continue to add to those totals on an ongoing basis

We need a strategy for where to store (and more importantly find) images.

Do we need a pair-tree, based on what (is OID sufficiently random - probably not)

**Comment by martinlovell** [comment]
One way to create the directory structure with equal distribution is to hash the filename.

The disadvantages of doing it this way is that the hash has to be calculated to locate the file, and it's not easily human-readable.

The advantage is that it will be equally distributed regardless of the filenames.
(The hash can be broken into different sized chunks depending on how many files you expect and how many files can be efficiently stored in one directory.)

```
  def self.calc_directory filename
    hash = Digest::MD5.hexdigest filename
    File.join(hash.scan(/.{1,2}/)).to_s
  end
```

**Comment by mikeapp** [comment]
This article on the Oxford Common File Layout mentions three approaches: flat, pairtree, n-tuple tree and gives examples.  https://www.mdpi.com/2304-6775/7/2/39/xml

**Comment by mikeapp** [comment]
Current discussion is pair tree but prefixed with last 2 digits, which gives an even distribution.
So:  `12345678` -> `/78/12/34/...` out to however many levels we need.

**Comment by mark-dce** [comment]
Mike - another option that might be programmatically simpler but have a similar effect is to just reverse the OID 12345678 --> 87654321.  I'm a fan of either option - they both put the bits with the most volatility in the most significant locations for good distribution across the tree.

**Comment by mikeapp** [comment]
Decision: we'll use the last two digits as a bucket, then generate the pair tree from the remainder of the oid.  OID 12345678  ->  78/12/34/56/12345678.tif

**Comment by mark-dce** [comment]
@mikeapp Should I be reading 'bucket' above in the literal S3 sense - i.e. we'd expect to have 100 separate buckets (00, 01, 02,...,98, 99), or are you just saying generically that by pre-pending the final two digits we get a nice broad top-level tree structure regardless of the storage solution?

**Comment by mikeapp** [comment]
Generic, not AWS.   Assuming we use Storage at Yale, with 100TB volume limits, DevOps can mount as many of those 100 top-level directories to each volume as makes sense.
