### ISSUE TITLE
Add all team GitHub IDs to repo

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/YUL-DC#18]
**ACCEPTANCE**
- [x] Confirm Github IDs  
- [x] YALE
    - [x] Ricardo Aliwalas - ra359
    - [x] Mike Appleby - mikeapp
    - [x] Keith Boyd-Carter - kbcarter
    - [x] Maura Carbone - dl-maura
    - [x] Eric DeJesus - edejesusyale
    - [x] Dale Hendrickson - daleatyale
    - [x] Rebecca Hirsch -rebeccahirsch
    - [x] Yue Ji - yjyale
    - [x] Martin Lovell - martinlovell
    - [x] Richard Lynch - rml55
    - [x] Bob Rice - bobrice
    - [X] Lakeisha Robinson - kcompsci
    - [x] Frederick Rodriguez - FCRodriguez7
    - [x] Katherine Sprague - ksprague25
    - [x] Maggie Zhao - MaggieZhaoYale
    - [ ] Anybody else?  
- [x] NOTCH8
    - [x] Julie Allinson - geekscruff
    - [x] JP Engstrom - jpengst
    - [x] Alisha Evans - alishaevn
    - [x] Rob Kaufman - orangewolf
    - [x] Kevin Kochanski - DraxIndustries79
    - [x] Anybody else? 
- [x] DCE
    - [x] Mark Bussey - mark-dce
    - [x] Max Kadel - maxkadel
    - [x] Rachel Kadel - fnibbit
    - [x] McClain Looney - mlooney
    - [x] Rachel Lynn - RachelDCE
    - [x] Bess Sadler - bess

**Comment by geekscruff** [comment]
please add jpengst and alishaevn

**Comment by mark-dce** [comment]
@mikeapp I'm striking out on finding user IDs for most of the Yale folks.  Could you ask someone from your team to round them up and drop them in a comment here OR update the main description above?

**Comment by mark-dce** [comment]
@DraxIndustries79 Can you check out the list of Notch8 folks in the ticket description above and let me know if I left anyone out who should have access to the project?

**Comment by DraxIndustries79** [comment]
Rebecca is probably good
Maura may need to make a new account (will update)
