### ISSUE TITLE
Sponsored Account Setup

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/YUL-DC#2]
First step:  Background check email from HireRight.  Expect a week or so before hearing after completion.

**ACCEPTANCE**
Team members can log in to Yale resources via VPN
- [x] Alisha
- [ ] ~Jez~ - see #39
- [x] JP
- [x] Julie
- [x] Kevin
- [x] Mark
- [x] Max
- [x] Bess
- [x] McClain
- [x] Rachel L
- [x] RMK

**Comment by DraxIndustries79** [comment]
Per Maura: Yale has our info and they will reach out to these individuals for next steps

**Comment by DraxIndustries79** [comment]
Yale ITS expected to experience delays related to COVID-19

**Comment by mikeapp** [comment]
I asked folks to check themselves off after activating their NetID but we should confirm VPN access is working.
