### ISSUE TITLE
Set up (temporary) UAT Environment for Manifest Service

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/YUL-DC#22]
**STORY**
So stakeholders and key users can interact with project output, the Product Owner would like a persistent UAT environment where folks can interact with the next proposed release of the system.

**ACCEPTANCE**
- [ ] There is a system accessible to all project team members (Yale, DCE, Notch8) where we can interact with the manifest service
- [x] We have mechanism to batch changes to the system into a "release"
- [x] We have a mechanism to deploy releases
- [ ] ~We have a mechanism to update content for the service (can be temporary/manual) https://github.com/curationexperts/YUL-DC/tree/notch8-manifests/manifests~  Will move to it's own ticket

- [ ]  ~add documentation for 1) local deploy, 2) CI deploy - IN PROGRESS~
- [ ] ~[BONUS] add a CI pipeline~

**Comment by mark-dce** [comment]
Provisional plan
* Set up a cluster using EKS (in the DCE Hosting org)
* We'll use the existing helm charts
* Write up documentation for other team members to be able to deploy changes (to code or content)
* [BONUS] setup a CI pipeline

**Comment by mikeapp** [comment]
Yale-accessible copy is at https://github.com/curationexperts/yul-dc-iiif-manifest

**Comment by mark-dce** [comment]
Service running on Kubernetes is available here
http://8ecaa646-marktestyuldciiif-494b-313263771.eu-west-1.elb.amazonaws.com

**Comment by geekscruff** [comment]
I know this is closed but putting this here as we don't have a CI ticket yet.

Steps are:

- docker build, tag, push
- deploy to kubernetes cluster (eg. by runing chart/bin/deploy script)
