### ISSUE TITLE
Recommend initial container deployment platform

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/YUL-DC#23]
**STORY**
So that Yale can make effective decisions about staff and service costs, the operations manager would like to better understand the options and trade-offs for various container deployment and management.

**DETAILS**
We have a comparison template set up here
https://docs.google.com/spreadsheets/d/1bwcnMCdd8EqBEivcRRm1dduN_Ymn-mRLz3YFmKkAbLg/edit#gid=0  
Please add any details and notes as your working on this and related tickets

**ACCEPTANCE**
- [ ] Identify potential container management options (EKS, ECS, Kubernetes on VMs, Kubernetes on bare metal, ???)
- [ ] Compare and contrast the different options using at least the following criteria
   - [ ] Cost (for comparable services - e.g. assume a IIIF server + Manifest server scenario)
   - [ ] Portability / Vendor Lock in (ease of porting to different solution in light of additional requirements)
   - [ ] Provisioning time
   - [ ] Complexity of setup
   - [ ] Complexity of operation
   - [ ] Observability (ease of monitoring, logging, tracing)
   - [ ] Ease of connection to Storage@Yale
   - [ ] Ease of connection to S3
   - [ ] Ease of connection to other storage service(s)
   - [ ] Other criteria ???
- [ ] Summarize key differences between options
- [ ] Provide a recommendation for the initial platform for us to start out on
- [ ] [BONUS] Articulate criteria which might cause us to want to change our decision in the future (i.e. what are the inflection points for the proposed solution?)

**Comment by geekscruff** [comment]
Slide deck for platform recommendations (inital wip): https://docs.google.com/presentation/d/1JhSgrg6owgjO5qU7I0MoZGjZWNLeyDDGzf_i15pZ7JY/edit#slide=id.p

**Comment by DraxIndustries79** [comment]
Agree to limit to Amazon or Azure for now

**Comment by ra359** [comment]
We met with Camden Fisher yesterday afternoon who is the lead engineer on Yale's SpinUp effort. He gave us a dog & pony of the container offering. Essentially a frontend for Amazon's Fargate/ECS offerings. He also said he can work w/ us to improve/extend the service as needed. He did nudge us towards object storage as it would theoretically be more performant due to proximity. We need to investigate StorageGrid/Wasabi/S3 options.

**Comment by DraxIndustries79** [comment]
Initial: AWS Kubernetes
