### ISSUE TITLE
Select initial IIIF server

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/YUL-DC#24]
**STORY**
In order to start developing consistent image solutions in development, UAT, and production environments, we need a containerized IIIF server that can be used in development, testing, CI/CD, and production environments.

*NOTE* The goal here is to make the best decision we can relatively quickly based on the information we have available now.  We should plan to be able to pivot should additional information surface later in the project that refines our understanding of the scope and constraints we're working in. 

**ACCEPTANCE**
- [x] Conduct a time bounded evaluation of IIP, Loris, Cantaloupe (+others?) and determine evaluation criteria to select one for use.  
Evaluation criteria should include 
- [x] Ease of containerization (or availability of existing images) - See #36 (Loris), #37 (Cantaloupe), #38 (IIP)
- [x] Ease of connecting to various image stores (local developer drive, server mount, Storage@Yale, EBS, S3)
- [x] Performance delivering PTIFFs - see #13
- [ ] Create a short write up of key differences between options, recommending one to move forward with
- [ ] BONUS Articulate the assumptions and criteria which might cause us to re-evaluate the decision in the future

**Comment by geekscruff** [comment]
Cantaloupe documentation on auth: https://cantaloupe-project.github.io/manual/5.0/access-control.html

**Comment by rebeccahirsch** [comment]
Has anybody reached out to the BL, Wellcome or Stanford about the auth bit? I've heard all three are using it. Here's an example from the BL: http://access.bl.uk/item/viewer/ark:/81055/vdc_000000021732.

**Comment by mikeapp** [comment]
Loris IIIF Auth code is apparently at https://github.com/loris-imageserver/loris/blob/development/loris/authorizer.py but no documentation that I could find.

**Comment by DraxIndustries79** [comment]
Probably closeable but let's check in with Mike next week
