### ISSUE TITLE
Containerization Level Up

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/YUL-DC#25]
**ISSUE**
We know we want to containerize the solution and build a corresponding deployment pipeline, but we don't all have the same level of experience and exposure to the various technologies and tools.

**QUESTIONS**
* Who else in the community (Samvera, IIIF, Blacklight) are using containers (and how)
* What are the options for managing containers in production
* Where are there some good tutorials
* Should we let some of the team be the vanguard and get something initial setup and then do a workshop with more concrete project-specific goals
* What does it look like to run figgy (or Valkyrie) generically in a container

**Comment by DraxIndustries79** [comment]
Coordinate a brown-bag knowledge sharing session lead by @geekscruff

**Comment by DraxIndustries79** [comment]
Placeholder for Wed 3/18

**Comment by mark-dce** [comment]
The slide deck from Julie's talk can be found here:
https://docs.google.com/presentation/d/16ICmc3ChRV21LpHBuceX-U5lYQvb7OTWg9cROlKytPg/edit#slide=id.g7f38dec43c_1_5
