### ISSUE TITLE
Setup Shared Slack Channel

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/YUL-DC#3]
**STORY**
As a team member, I'd like a lightweight tool that helps me communicate both synchronously and asynchronously with other team members, in order to reduce barriers to collaboration on the project.

**ACCEPTANCE**
- [x] We have a place in Slack where team members form all three organizations can interact

Add the following folks (note - these are GitHub IDs, not slack ids)
- [ ] YALE
    - [x] Ricardo Aliwalas - ra359
    - [x] Mike Appleby - mikeapp
    - [x] Keith Boyd-Carter - kbcarter
    - [x] Maura Carbone
    - [x] Eric DeJesus - edejesusyale
    - [ ] Dale Hendrickson - daleatyale (OPTIONAL/LATER per Mike Appleby)
    - [x] Rebecca Hirsch -rebeccahirsch
    - [x] Yue Ji - yjyale
    - [x] Martin Lovell - martinlovell
    - [ ] Richard Lynch - rml55 (OPTIONAL/LATER per Mike Appleby)
    - [x] Bob Rice - bobrice
    - [x] Lakeisha Robinson - kcompsci
    - [x] Frederick Rodriguez - FCRodriguez7
    - [x] Katherine Sprague - ksprague25
    - [x] Maggie Zhao - MaggieZhaoYale
    - [ ] Anybody else?  
- [x] NOTCH8
    - [x] Julie Allinson - geekscruff
    - [x] JP Engstrom - jpengst
    - [x] Alisha Evans - alishaevn
    - [x] Rob Kaufman - orangewolf
    - [x] Kevin Kochanski - DraxIndustries79
    - [x] Anybody else? 
- [x] DCE
    - [x] Mark Bussey - mark-dce
    - [x] Max Kadel - maxkadel
    - [x] Rachel Kadel - fnibbit
    - [x] McClain Looney - mlooney
    - [x] Rachel Lynn - RachelDCE
    - [x] Bess Sadler - bess

**Comment by mikeapp** [comment]
I now have admin rights on the Yale Library IT Slack channel.  I can see the Shared Channels option in the account.   

Looks like shared channels are limited to joining two orgs:
"Shared channels let **two** separate organizations work together in a single channel, each from their own Slack workspace. They can be public or private, but they're only available for paid plans."

**Comment by DraxIndustries79** [comment]
I see what Michael sees - only two per shared channel.  Options are left to:

1. Sharing in the Samvera Slack
2. Keeping our shared channel and individually inviting guests of whichever organization has the smallest team.

Option 2 means one organization would have to set up a new workspace anyway, yes?  I feel like making a channel in Samvera evens the field since we're all likely ducking in there regularly anyway.

**Comment by mark-dce** [comment]
@DraxIndustries79 Can you add instruction for anyone who doesn't have a Samvera slack acount yet?

**Comment by DraxIndustries79** [comment]
For joining Samvera slack:
http://slack.samvera.org/ 

Invitation instructions are there.

**Comment by mark-dce** [comment]
I just set up a shared private channel and added Kevin, Julie, Rob, and Bess
samvera#yale-libraries
https://slack.com/share/IUW3F0JJ1/1nS8YtjJobb2xo9QOf4twCiP/enQtOTgyMTE3MDE4NjEzLTEyNDg5Yjc2YTYxNDczYzEyMjU2N2UxZjU1ZmVkYWVhNWFkNzY0MmMzMmZjNGExNTE3ZTZlY2M2Y2IzYTViOGM

@DraxIndustries79 I added all the project folks to the ticket description - are you able to add/invite them all to the channel?

**Comment by DraxIndustries79** [comment]
@mark-dce First time on Zendesk myself, so apologies if it's user error, but I'm not able to tag most of the folks I want to on the list above (if there's a place to see that they are or are not a part of this workspace, I wasn't able to find it).  

Folks (will tag those I can), I invited to the slack channel in Samvera, but couldn't find users for the following - will check back tomorrow as several folks I'm sure need to join Samvera slack first. 

Ricardo Aliwalas - ra359
Dale Hendrickson - daleatyale 
Rebecca Hirsch -rebeccahirsch 
Yue Ji - yjyale
Richard Lynch - rml55
Lakeisha Robinson - kcompsci 
McClain Looney - @mlooney 

Maggie Zhao - MaggieZhaoYale - Maggie you have two Samvera slack accounts (maggie.zhao@yale.edu and lixia.zhao@yale.edu) - let me know which to invite.

**Comment by MaggieZhaoYale** [comment]
@DraxIndustries79 maggie.zhao@yale.edu.  Thank you.

**Comment by yjyale** [comment]
Hello,
I (Yue Ji – yjyale) joined Samvera slack. What should I do next?
Thanks,
Yue
