### ISSUE TITLE
SSL for Manifest Service

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/YUL-DC#31]
**STORY**
As a researcher, I would like to be able to use data from the manifest service to view works in Universal Viewer, so that I have an easy way to page through and manipulate the images in the work.

**DETAILS**
Universal Viewer transmits all manifest requests via HTTPS and, therefore, requires the manifest service to support SSL/TLS in order to load manifest data.

**ACCEPTANCE**
- [ ] I can view the sample manifest for 16854582 in Universal viewer using the manifest service

**BEFORE**
When I visit https://universalviewer.io/uv.html?manifest=http://8ecaa646-marktestyuldciiif-494b-313263771.eu-west-1.elb.amazonaws.com/manifests/16854582.json, I get the following behavior
![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/3ca7bbb7-2428-4dee-92f0-a41158149b39)

**AFTER**
The work displays as expected

**Comment by DraxIndustries79** [comment]
Per Julie, we may get a quick answer from Rob K on this

**Comment by mark-dce** [comment]
We've got HTTPS running at https://yul-dc.curationexperts.com/manifests/

But seem to have CORS issues  
![image](https://user-images.githubusercontent.com/3064318/77453699-93919d00-6dc5-11ea-8082-2ca51f5a14cf.png)
