### ISSUE TITLE
PTIFFs for Sample Images

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/YUL-DC#33]
**ISSUE**
To support initial testing and experimentation, we'd like pyramidal derivatives of the sample TIFFs identified in #32

**ACCEPTANCE**
- [x] We have a separate S3 Bucket for PTIFFs
- [ ] For each source tiff in the main image bucket, we have a corresponding ptiff in the new bucket

**Comment by mikeapp** [comment]
About 4,000 images generated, rest should be there by the end of the day.

**Comment by mikeapp** [comment]
9042 PTIFFs generated and stored in S3

![Screen Shot 2020-03-26 at 10.37.55 AM.png](https://images.zenhubusercontent.com/5e5d472f410278efd81466ab/d7dd6e37-7b49-43ac-89b5-f7f83f5afce4)
