### ISSUE TITLE
Develop Comparison template

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/YUL-DC#35]
**ACCEPTANCE**
- [x] Develop a platform comparison template covering the items listed in #23
- [x] Identify initial services to compare

**Comment by mark-dce** [comment]
- [ ] Compare and contrast the different options using at least the following criteria
   - [ ] Cost (for comparable services - e.g. assume a IIIF server + Manifest server scenario)
   - [ ] Portability / Vendor Lock in (ease of porting to different solution in light of additional requirements)
   - [ ] Provisioning time
   - [ ] Complexity of setup
   - [ ] Complexity of operation
   - [ ] Observability (ease of monitoring, logging, tracing)
   - [ ] Ease of connection to Storage@Yale
   - [ ] Ease of connection to S3
   - [ ] Ease of connection to other storage service(s)
   - [ ] Other criteria ???

**Comment by dl-maura** [comment]
Here is the template! If you want to add things and can't please let me know

https://docs.google.com/spreadsheets/d/1bwcnMCdd8EqBEivcRRm1dduN_Ymn-mRLz3YFmKkAbLg/edit?usp=sharing
