### ISSUE TITLE
SPIKE: Add a Loris-based IIIF service to an existing Kubernetes cluster

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/YUL-DC#36]
NOTE 1: This is a spike, time box it to 1 day or less and document outcomes

NOTE 2: For now, use any images - images from our s3 bucket are great [yale-image-samples/originals](https://s3.console.aws.amazon.com/s3/buckets/yale-image-samples/originals/?region=us-east-1&tab=overview) feel free to copy these to a local volume, EFS, or wherever is easiest to mount.

**ACCEPTANCE**
- [ ] I can deploy Loris to an existing k8s cluster
OR 
- [ ] Document how far you got in the process and list the blockers

**QUESIONS**
- [x] Are there any publicly available Loris images
- [x] How much configuration needs to be done
- [x] What kind of file stores are easiest to set up
- [ ] Make a note of any other questions that come up during setup

**Comment by edejesusyale** [comment]
Can someone assign this to me, I don't have permissions to do so.

**Comment by mark-dce** [comment]
@edejesusyale can you accept the invite you should see at this link: https://github.com/curationexperts/YUL-DC/invitations (you should also have an e-mail with the invite).  You'll need to accept the invite and then you should have access to the repo.

**Comment by FCRodriguez7** [comment]
**First step; search for Publicly available Docker Loris images:**

1. https://github.com/loris-imageserver/loris-docker
2. https://github.com/bodleian/loris-grok-docker
3. https://hub.docker.com/r/lorisimageserver/loris/dockerfile [written by Princeton U]

**Comment by FCRodriguez7** [comment]
**Second step: 
How much configuration needs to be done for a functional docker container?**

Frederick & Eric paired for about an hour on building a docker file.

**Comment by FCRodriguez7** [comment]
Step three:  
What kind of file stores are easiest to set up?
[work in progress]

**Comment by FCRodriguez7** [comment]
Reading about Kubernetes cluster: https://kubernetes.io/docs/concepts/overview/what-is-kubernetes/

**Comment by FCRodriguez7** [comment]
Progress on steps two and three: 

There is a working docker container if you access or secret key does not have a special character in it.  Additionally,  we were able to get s3 images to appear and cached on the image server.

**Comment by FCRodriguez7** [comment]
**Step Three:** 

A decision was made for type of file storage.
