### ISSUE TITLE
SPIKE: Add a Cantaloupe-based IIIF service to an existing k8s cluster

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/YUL-DC#37]
NOTE 1: This is a spike, time box it to 1 day or less and document outcomes

NOTE 2: For now, use any images - images from our s3 bucket are great [yale-image-samples/originals](https://s3.console.aws.amazon.com/s3/buckets/yale-image-samples/originals/?region=us-east-1&tab=overview) feel free to copy these to a local volume, EFS, or wherever is easiest to mount.

**ACCEPTANCE**
- [ ] I can deploy Cantaloupe to an existing k8s cluster
OR 
- [ ] Document how far you got in the process and list the blockers

**QUESIONS**
- [x] Are there any publicly available Cantaloupe images
- [x] How much configuration needs to be done
- [x] What kind of file stores are easiest to set up
- [ ] Make a note of any other questions that come up during setup

**Comment by FCRodriguez7** [comment]
First step search for:
**Publicly available Docker Cantaloupe images:**

1. https://github.com/MITLibraries/docker-cantaloupe
2. https://github.com/ExLibrisGroup/alma-cantaloupe
3. https://hub.docker.com/r/mitlibraries/cantaloupe/
4. https://hub.docker.com/r/joshmweisman/alma-cantaloupe/

**Comment by FCRodriguez7** [comment]
Second Step:  
How much configuration needs to be done?

We used the MIT Libraries Cantaloupe docker for configuring the image server.  We got a working server by noon with s3 images, but no caching.

I will push the code that has the modifications up to the yale enterprise git.  And paste in the link: [here].

We could look at the flex-share file structure native to Yale's IT environment next.

**Comment by FCRodriguez7** [comment]
Third Step: 
**What kind of file stores are easiest to set up?**

The initial setup of the server was with s3.  

We could look at the flex-share file structure native to Yale's IT environment next.

**Comment by FCRodriguez7** [comment]
Last night, I was able to get s3 cache working.   I have pushed up the new code with the s3 cache working to https://github.com/FCRodriguez7/docker-cantaloupe.

**Comment by FCRodriguez7** [comment]
**Step Three:** 

A decision was made for type of file storage.
