### ISSUE TITLE
SPIKE: Add an IIP-based IIIF service to an existing k8s cluster

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/YUL-DC#38]
NOTE 1: This is a spike, time box it to 1 day or less and document outcomes

NOTE 2: For now, use any images - images from our s3 bucket are great [yale-image-samples/originals](https://s3.console.aws.amazon.com/s3/buckets/yale-image-samples/originals/?region=us-east-1&tab=overview) feel free to copy these to a local volume, EFS, or wherever is easiest to mount.

**ACCEPTANCE**
- [ ] I can deploy IIP to an existing k8s cluster
OR 
- [ ] Document how far you got in the process and list the blockers

**QUESIONS**
- [x] Are there any publicly available IIP images
- [ ] How much configuration needs to be done
- [ ] What kind of file stores are easiest to set up
- [ ] Make a note of any other questions that come up during setup

**Comment by geekscruff** [comment]
Are there any publicly available IIP images?
* https://github.com/bodleian/iipsrv-openjpeg-docker (not in dockerhub, last commit 2018)
* https://hub.docker.com/r/antage/iipimage-server (highest downloads, updated 2 years ago)
* https://hub.docker.com/r/dfukagaw28/iipsrv (newest, updated 14 days ago)

**Comment by FCRodriguez7** [comment]
Read about the software product: https://iipimage.sourceforge.io

**Comment by DraxIndustries79** [comment]
Probably not essential considering info from the other tickets.
