### ISSUE TITLE
Core Team Members understand the IIIF Presentation API

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/YUL-DC#4]
**STORY**
*(**NEW** form - benefit first)*
In order for the team to have efficient, effective conversations about structural metadata requirements going forward, as the product owner, I want to ensure that every member of the development team understands how to construct a IIIF Manifest.

>*(**OLD** form - as a {role}, I want {functionality}, so that {benefit} - benefit/outcome last)*
As a product owner, I want everyone on the development team to understand how to construct a IIIF manifest, so that we can have efficient and effective conversations about structural metadata requirements going forward.

**DETAILS**
For now, we'll assume the project will be using the IIIF Presentation API 2.0 https://iiif.io/api/presentation/2.0/.  (During future sprints, we'll identify whether any of the features of later 2.x versions of the API are required to support features desired in the system and which, if any, existing IIIF servers support those features)

In addition to the API definition itself, folks may find the online tutorial at https://ronallo.com/iiif-workshop/presentation/ very helpful.

There are sample objects in BRBL DL to work with in the list here https://app.box.com/notes/624396473641
or this Google doc copy for folks not on the box access list
https://docs.google.com/document/d/1rKyqq3UjNs2A0lWgoEJFEHwDf8-ZFNf0V8sYE8h1SUE/edit?usp=sharing

**ACCEPTANCE**
Given an ordered set of links representing the pages of a manuscript or other paginated work, each member will construct a corresponding IIIF manifest that can be viewed in a Universal Viewer or Mirador instance.  The manifest should include the following minimal work-level metadata:
* Title
* Creator / Author
* Date

Finished manifests should be linked to this ticket.
- [x] Mark
- [x] Mike
- [x] Martin
- [x] Eric
- [ ] McClain
- [ ] Julie
- [ ] JP

*BONUS*
- [x] Bess
- [ ] Kevin
- [ ] Alisha
- [ ] Kaylee
- [ ] Lakeisha
- [ ] Maura
- [ ] Rebecca
- [ ] Frederick

**Comment by geekscruff** [comment]
Also, ruby gem for creating iiif manifests if folks want to write code: https://github.com/samvera/iiif_manifest

although this is a Samvera gem, it is in no way dependent on Hyrax / Valkyrie etc.

**Comment by geekscruff** [comment]
Validator https://iiif.io/api/presentation/validator/service/

**Comment by mark-dce** [comment]
👍 having a validator is awesome - I didn't know about that.

**Comment by kcompsci** [comment]
Hi Mark. Can you add Frederick's name to the _BONUS_ section? I tried to add it myself but I don't think I can.

**Comment by edejesusyale** [comment]
Hey Mark, I do not have access to the list of BRBL objects. My email is eric.dejesus@yale.edu.

**Comment by mikeapp** [comment]
I also need access to the object list (assuming it's the Box note above).

**Comment by geekscruff** [comment]
and me ...

**Comment by mikeapp** [comment]
I'm hitting CORS issues with requests for image `info.json`.   After Mirador didn't work I tried the UCD image crop tool, which works with individual images.

Example base URL:
https://brbl-zoom.library.yale.edu/fcgi-bin/iipsrv.fcgi?IIIF=MEDRENMSSX02/6/11077086/11077086.jp2

...and its `info.json`:
https://brbl-zoom.library.yale.edu/fcgi-bin/iipsrv.fcgi?IIIF=MEDRENMSSX02/6/11077086/11077086.jp2/info.json

...in the cropping tool:
https://jbhoward-dublin.github.io/IIIF-imageManipulation/index.html?imageID=https://brbl-zoom.library.yale.edu/fcgi-bin/iipsrv.fcgi?IIIF=MEDRENMSSX02/6/11077086/11077086.jp2

JS console reports `Origin https://jbhoward-dublin.github.io is not allowed by Access-Control-Allow-Origin.`.

**Comment by mark-dce** [comment]
@mikeapp we've run into similar issues in the past

The issue report below describes a potential solution:
>Adding "Access-Control-Allow-Origin" with a value of "*" to your IIIF resource responses should fix this.
https://github.com/ArchiveLabs/iiif.archivelab.org/issues/4

I don't know whether it's worth addressing this with the existing image server.  Alternatively, we could complete the exercise knowing that images won't load because of the CORS issue and then update the manifests once we have a working image service.

**Comment by mark-dce** [comment]
@mikeapp @edejesusyale - it looks like not everyone has access to the box note; I'll work with Maura to get that fixed.  In the meantime, I made a copy of the information in a google doc that should be accessible https://docs.google.com/document/d/1rKyqq3UjNs2A0lWgoEJFEHwDf8-ZFNf0V8sYE8h1SUE/edit?usp=sharing

**Comment by mikeapp** [comment]
I took "Mirour of mans salvacioune." from the "large works" list ( https://brbl-dl.library.yale.edu/vufind/Record/4340604?object_id=16156712 ).  I published the Manifest to a repo with GitHub Pages turned on but will create a PR.  

Note that having an `@id` for the Manifest that doesn't match the actual URL can cause issues in the client (at least it used to with Mirador...), so we might want to consider a new GitHub Pages-enabled repo to allow for more convenient testing.

Manifest: 
https://mikeapp.github.io/static/iiif/manifest/10269867.json
View: 
http://mirador.britishart.yale.edu/?manifest=https://mikeapp.github.io/static/iiif/manifest/16156712.json

Note that the thumbnails do display since they are direct links to IIIF Image API URLs (Mirador treats them as they would a link to a static image file).

**Comment by mark-dce** [comment]
Here's mine - from the 8.2.4 Box-level archive (partially-digitized)
Original: https://brbl-dl.library.yale.edu/vufind/Record/4727766?object_id=16854582
Manifest: https://gist.github.com/mark-dce/5ca1d6b5f4820c2390748e50a7ad89ac

It validates (with warnings) and displays in UV, but Mirador doesn't like it probably because of the missing images and IDs (for non-photographed pages)
https://universalviewer.io/uv.html?manifest=https://gist.githubusercontent.com/mark-dce/5ca1d6b5f4820c2390748e50a7ad89ac/raw/2b16f8ce27a63da5bc78d4d8fd0dc52d1b11888c/16854582.json#?c=0&m=0&s=0&cv=0&xywh=-2823%2C-214%2C8645%2C4263

**Comment by martinlovell** [comment]
Here are a few manifests generated from the Ladybird database.

https://martinlovell.github.io/sample-manifests/

They validate on the IIIF validator; however, they point the not existing iiif-central.yale.edu for images and info.json, so they don't work in viewers.

(As an experiment, I generated some structures based on the caption names for pages using regex.)

(It would be nice if we setup a IIIF image server that pulled public source images from the BRBL dl, FindIt Image server, or Fedora (without worrying about quality/performance/security etc for now) so we could experiment with BRBL images by OID.)

**Comment by bess** [comment]
Here is mine, for this work: https://brbl-dl.library.yale.edu/vufind/Record/4161660
I did a right-to-left Arabic mss.
Manifest here: https://gist.github.com/bess/e5bce5e1445853734835e04cac5074a6
I downloaded the images and put them into a local Cantaloupe instance so I could see the right-to-left paging in action: 

![rtl_small.png](https://images.zenhubusercontent.com/5ca3a84155cfe32f2f66b74c/dcad32ba-0fdc-43f1-8117-9be966956730)

**Comment by edejesusyale** [comment]
Manifest: https://edejesusyale.github.io/static/iiif/manifest/16371253.json
Viewer: http://mirador.britishart.yale.edu/?manifest=https://edejesusyale.github.io/static/iiif/manifest/16371253.json

**Comment by mark-dce** [comment]
I've made a PR to add all the samples (just one of Martin's for expediency 😉 )
https://github.com/curationexperts/YUL-DC/pull/21

**Comment by alishaevn** [comment]
**Work**: https://brbl-dl.library.yale.edu/vufind/Record/4428123?object_id=16371272
**Manifest**: https://raw.githubusercontent.com/curationexperts/YUL-DC/notch8-manifests/manifests/16371272.json

![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/c6a2bac4-3fd4-49b9-a855-120c1c4f1daa)
