### ISSUE TITLE
Get folks on VPN

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/YUL-DC#43]
- [ ] Folks can install and launch Cisco ConnectAnywhere

**Comment by mark-dce** [comment]
@mikeapp - would it be worth trying to have one of the yale folks download the MacOS flavored installer from https://software.yale.edu/software/cisco-vpn-anyconnect and sending it to one of us via SneakerNet (e-mail, S3, FTP) and see if that works?

**Comment by mikeapp** [comment]
We have permission to do just that - Maura received an OK yesterday.

**Comment by mark-dce** [comment]
I've been able to connect successfully using the client, my NetID, and Duo 2-factor.
<img width="430" alt="image" src="https://user-images.githubusercontent.com/3064318/78053020-96e8d380-7345-11ea-851a-29f2d930e263.png">

**NOTE**
At various points it's taken me multiple attempts to connect (I suspect because all licensed connections are in use) and I get a very misleading error when I can't connect
<img width="420" alt="image" src="https://user-images.githubusercontent.com/3064318/78053290-01017880-7346-11ea-9b17-297923d6c967.png">

**Comment by DraxIndustries79** [comment]
Looks like an issue just for external folks.  Maura will file a ticket.

**Comment by DraxIndustries79** [comment]
Yale's having some growing pains here in general.

**Comment by mikeapp** [comment]
Requests have been submitted and approved, now waiting for ITS action/confirmation.

**Comment by geekscruff** [comment]
All working for me.

**Comment by alishaevn** [comment]
I was able to get in. :) 

![image.png](https://images.zenhubusercontent.com/5e5ea9bffa78052c1cbcc74f/681b41f4-c124-459b-a4a8-d1b679d6e156)

**Comment by mikeapp** [comment]
All account have been activated by ITS.
