### ISSUE TITLE
Team Teach Out: ECS vs EKS

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/YUL-DC#44]
**ISSUE**
We'd like to level up as a team on the differences between Amazon's *Elastic **Container** Service* and *Elastic **Kubernetes** Service*

**ACCEPTANCE**
- [ ] Spend up to 6 hours researching blogs, white papers, and videos on the topic
- [ ] Curate a list of your favorite resources
    - [ ] At least one short written guide (<10 minute read)
    - [ ] At least one short video (<8 minutes duration)
    - [ ] One deeper dive into the topic
    - [ ] Up to two additional resources
- [ ] Prepare a 7 minute lightning talk to give to the team next week

**Comment by dl-maura** [comment]
https://docs.google.com/document/d/1-3yXGMD0sZp5dM_vnexW1jCet81lLheB12cwkdl6KsA/edit?usp=sharing

**Comment by bess** [comment]
Slide deck here: https://docs.google.com/presentation/d/1aXr7cUoXTSaskXGxgek8LXs8zUmzdpaEHjBkHb5N7R4/edit?usp=sharing
