### ISSUE TITLE
Team Teach Out: Kubernetes

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/YUL-DC#45]
**ISSUE**
We'd like to level up as a team on what **Kubernetes** is and what it does compared to more traditional infrastructure models.

**ACCEPTANCE**
- [x] Spend up to 6 hours researching blogs, white papers, and videos on the topic
- [x] Curate a list of your favorite resources
    - [x] At least one short written guide (<10 minute read)
    - [x] At least one short video (<8 minutes duration)
    - [x] One deeper dive into the topic
    - [x] Up to two additional resources
- [x] Prepare a 7 minute lightning talk to give to the team next week

**Comment by dl-maura** [comment]
https://docs.google.com/document/d/1-3yXGMD0sZp5dM_vnexW1jCet81lLheB12cwkdl6KsA/edit?usp=sharing

**Comment by mlooney** [comment]
links provided on above gdoc
