### ISSUE TITLE
Team Teach Out: What is a container

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/YUL-DC#51]
**ISSUE**
We'd like to level up as a team on the benefits of containerization.  Using Julie's presentation from the other week as a jumping off point, we'd like a few other resources to help understand the topic more deeply

**ACCEPTANCE**
- [x] Spend up to 6 hours researching blogs, white papers, and videos on the topic
- [x] Curate a list of your favorite resources
    - [x] At least one short written guide (<10 minute read)
    - [x] At least one short video (<8 minutes duration)
    - [x] One deeper dive into the topic
    - [x] Up to two additional resources
- [ ] Prepare a 7 minute lightning talk to give to the team next week

**Comment by dl-maura** [comment]
https://docs.google.com/document/d/1-3yXGMD0sZp5dM_vnexW1jCet81lLheB12cwkdl6KsA/edit?usp=sharing
