### ISSUE TITLE
Gather Metadata for Voyager Objects

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/YUL-DC#53]
**ACCEPTANCE**
For the works listed in ... that come from Voyager
- [ ] Store a metadata record (JSON?) for each work in the `Voyager` bucket on S3

**Comment by yjyale** [comment]
Mark,
I am working on two sets of sample JSON files. One is for LadyBird's records, another is for Voyager's records. How would you like to send it, email or slack?
Yue

**Comment by mikeapp** [comment]
Files in `voyager` folder
