### ISSUE TITLE
Document Current Architecture Assumptions

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/YUL-DC#56]
**ACCEPTANCE**
- [x] Show public endpoints
- [x] Show anticipated services / pods / tasks
- [x] Show internal attachments (S3, Storage@Yale, metadata)

- [x] Circulate for comment & review

**Comment by mark-dce** [comment]
Work-In-Progress
https://www.lucidchart.com/invitations/accept/42891c62-0db2-426f-bebe-79668b1819bc

**Comment by geekscruff** [comment]
@mark-dce I really like the way this is looking!
