### ISSUE TITLE
SPIKE: Containerize Manifest Service

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/YUL-DC#8]
**QUESTION**
What does it take for us to build a containerized IIIF manifest service that can:
1. Run on a developer's local system
2. Run in a CI/CD pipeline
3. Run in a VPN protected UAT environment
4. Run in a production environment accessible via the public internet

**Comment by geekscruff** [comment]
See: https://github.com/notch8/yul-dc-iiif-manifest

**Comment by geekscruff** [comment]
PR https://github.com/notch8/yul-dc-iiif-manifest/pull/1
