### ISSUE TITLE
SPIKE: IIIF Manifest storage estimate

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/YUL-DC#9]
**STORY**
As a systems owner, I'l like a ballpark estimate of the total amount of storage Yale should plan on allocating to store IIIF manifests for BRBL, so that I can begin planning and estimating the cost of using dedicated storage, EBS, S3 or other storage solutions.

**ACCEPTANCE**
- [x] Develop model for estimating IIIF manifest size based on number of images included
- [x] Develop a distribution model for existing BRBL content based on number of images per work
- [x] *Estimate* a predicted overall growth rate from now through December 31, 2020
- [x] Calculate a total storage requirement based on the models and estimates
- [x] *Guesstimate* the expected accuracy of the calculation as a percentage of the total (e.g. +/- 50%, +25%/-10%, +/-15%, etc.)

**Comment by mark-dce** [comment]
Probably just total number of works = size of containing json
+
Total number of images * size of stanza for one page image

**Comment by mikeapp** [comment]
I'm seeing 1.5K per Canvas, but perhaps round up to 2K:
2048 * 4000000 / (1024 * 1024) = 7812.5 MB
